### ISSUE TITLE
Proposal : tag information

### ISSUE THREAD

**Issue by soupfv** [diogocavilha/fancy-git#105]
Hello, 
First of all, thank you for this great work!

I wanted to know if it was possible to display the current tag next to HEAD?

![image](https://user-images.githubusercontent.com/23630214/153193144-4cde88fd-3af2-4f1c-a089-a260f9b50c47.png)
![image](https://user-images.githubusercontent.com/23630214/153193197-84fec868-2e52-4cbe-9737-aced0cd88411.png)

Also, would it be possible to customize the user@host?

**Comment by diogocavilha** [comment]
Hi, @dquartino 

Thank you for proposing new features.

Yes, that's totally possible. If you're working on it already, please let me know. Otherwise I'll start working on it. Having the tag info is really a missing feature! Thank you for that.

Regarding to user@host, it's possible to customize it by config but I didn't get what exactly you wish to customize.

**Comment by diogocavilha** [comment]
Oh! I've just seen your PR!

Thank you so much. I'll be reviewing that on next few days.
