### ISSUE TITLE
Disable auto update checks feature

### ISSUE THREAD

**Issue by cgomesu** [diogocavilha/fancy-git#118]
I find the automatic update checks a bit intrusive and would like to disable it.  I know we can always comment out the part of the script that checks for updates but it would be way more convenient if it could be disabled via an argument, such as `--disable-update-checks`. 

Is there any chance this feature could be implemented?

Thanks for all the work!

**Comment by diogocavilha** [comment]
Hi, @cgomesu 

Thank you for your suggestion.

Yes, that feature may be implemented, no doubt. But bear in mind you might end up with an FancyGit version easily.

**Comment by cgomesu** [comment]
I understand the drawback associated with disabling automatic update checks but I also feel shell environments are fairly stable over time and if one gets FancyGit working once, the script should work as initially intended for a long time without any further updates.  There are also security concerns regarding auto updates from a repo (`diogocavilha/fancy-git`) that is not under control of the user, even though `fancy-git` is not running as `root` and does not require `root` permission at any point.  In any case, I just feel like a simple `--enable`/`--disable` arg for the auto update feature could be helpful for users who do not have the time to look into the scripts and disable the update function manually.

(Sempre legal achar outro brasileiro compartilhando esses tipos de projetos.  O meu comentário é só uma sugestão.  Nada pessoal ou que precisa ser implementado.  Obrigado por compartilhar o projeto!)

**Comment by diogocavilha** [comment]
Hi, @cgomesu 

Thank you for your point, I really appreciate that.
Enabling/disabling auto updates might be a feature for next versions, for sure.

For now, you may run `sed -i 's/check_for_update/#check_for_update/' .fancy-git/themes/*.sh` in order to disabling it for you.

FancyGit comes with `--update` command. So you can still update it whenever you want.

(Muito obrigado! Toda sugestão é sempre bem vinda. Fico muito contente em saber que esse projeto esteja sendo útil pra mais desenvolvedores. Infelizmente eu não consigo me debruçar sobre ele o tempo que gostaria, mas sempre que posso, estou tentanto melhorar alguma coisa por aqui.)
