### ISSUE TITLE
Binding for viewing currently active virtual environment

### ISSUE THREAD

**Issue by romunov** [diogocavilha/fancy-git#34]
With the new icon indicating active python virtual environment (see #28), a command that would display current working virtual environment would be a great addition. @diogocavilha has suggested `gpvd` (g-present virtual directory). Another option that is, for me, a bit easier to type, would be `gpve` (g-present virtual environment).

I was thinking of a hover-over feature for this, but that's probably more of the terminal feature than bash.

**Comment by diogocavilha** [comment]
> With the new icon indicating active python virtual environment (see #28), a command that would display current working virtual environment would be a great addition. @diogocavilha has suggested `gpvd` (g-present virtual directory). Another option that is, for me, a bit easier to type, would be `gpve` (g-present virtual environment).

Perfect! `gpve` is really a better choice.

> I was thinking of a hover-over feature for this, but that's probably more of the terminal feature than bash.

Yes, that would be cool but unfortunately it's a terminal feature.

**Comment by diogocavilha** [comment]
@romunov now that I'm implementing this new command, I just realized that the letter `g` at the begining of every fancygit alias is because of `git`, like `gcm` -> `git commit` or `gaa` -> `git add --all`. That means some `git action`.

So, here I think your first suggestion would be ok, like `pve`. Because this one is not a `git action`.

**Comment by romunov** [comment]
Even better. :)
