### ISSUE TITLE
SourceCodePro+Powerline+Awesome fonts not appearing in gnome-terminal font select

### ISSUE THREAD

**Issue by Slashfic** [diogocavilha/fancy-git#73]
Maybe this is a problem with gnome terminal instead of fancy-git, but the SourceCodePro fonts don't appear as a custom font in gnome-terminal, even though they do appear in gnome-tweaks.

**Comment by diogocavilha** [comment]
Hello @Slashfic 

Doesn't that appear even after running `fc-cache -fv` and restarting the gnome-terminal? 
If the font appears in any other font config on the system, it might be a gnome-terminal issue, but... it sounds weird anyway.

**Comment by diogocavilha** [comment]
Hi @Slashfic, I'm making some tests with another font, maybe it solves the problem you're facing.
You can see the discussion right here... #70 

I'll release a test branch soon. So you could test it there, in order to check if it solves it or not.
Would help me on that? May I ask you to test it when I release the branch?

**Comment by Slashfic** [comment]
Yeah let me know when it's released

**Comment by diogocavilha** [comment]
Hi, @Slashfic, feel free to pull the branch 6.3.x.

After pulling it, please run fancygit configure-fonts in order to install the new font called Sauce-Code-Pro-Nerd-Font-Complete-Windows-Compatible.ttf, which is one of the Nerd Fonts collection. At this commit, the goal is to keep FancyGit working as it should do. Just in order to fix the problems you're facing there.

Don't forget to change the terminal font to the Sauce Code.

**Comment by Slashfic** [comment]
Unfortunately it's not working still. Is there any more information I can give you that would be helpful?

**Comment by diogocavilha** [comment]
Hi, @Slashfic. Hope you are doing good.

Are you still facing that problem?

**Comment by Slashfic** [comment]
I just reinstalled, and it seems to be working ok

**Comment by diogocavilha** [comment]
Oh, that's perfect. Thank you!
